### ISSUE TITLE
Download proceeds even after clicking cancel

### ISSUE THREAD

**Issue by EmiliaBlasten** [CraigChat/craig#27]
In the new website, clicking cancel after clicking any of the download recording buttons still makes the download proceed in the background. It's just not saving the files to disk. This wastes bandwidth. See the following gif:
![craig_download_bug](https://user-images.githubusercontent.com/46397121/153713557-e08c6d56-6a66-488d-9529-a9f67a1989b4.gif)

Furthermore after that, all the download buttons fail giving the following error. Thus downloading the recording  becomes impossible.
![Screenshot_from_2022-02-12_15-34-05](https://user-images.githubusercontent.com/46397121/153713611-11afa1cd-f52e-46b2-b014-876d3c05f132.png)

**Comment by EmiliaBlasten** [comment]
Addition:

Waiting does not make the download buttons work after clicking cancel. Downloading the recording using wget makes them work. No matter how long you wait, the buttons stay in the "an error occured" state until the recording is downloaded using wget.

**Comment by Snazzah** [comment]
Forgot about this issue. The way downloads work pretty much solved this.
