### ISSUE TITLE
[feature request] Confirmation / messaging on Craig auto-upload to Google Drive

### ISSUE THREAD

**Issue by KuraFire** [CraigChat/craig#8]
Craig has been a wonderful resource, and the auto-upload to Google Drive is amazingly useful! It would be even more awesome if Craig would message a confirmation or error message upon completion of a recording, letting you know whether the recording successfully uploaded or if there was an issue. (And maybe, if possible, also share a link to the recording on GDrive)

Is this doable? Would it be too verbose? Could enabling this be a toggleable flag?

**Comment by Snazzah** [comment]
*Although this is weird to comment on a 2 year old issue,* This will be added in version 2.
